### ISSUE TITLE
SLF4J multiple bindings when following documentation with 5.13.2 version

### ISSUE THREAD

**Issue by natrem** [mock-server/mockserver#1308]
**Describe the issue**
Similar to #1278 I encounter issues when using *mockserver-junit-jupiter-no-dependencies*.
It works fine when using *mockserver-junit-jupiter*.

Execution logs SLF4J binding issue:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:xxx/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:xxx/.m2/repository/org/mock-server/mockserver-junit-jupiter-no-dependencies/5.13.2/mockserver-junit-jupiter-no-dependencies-5.13.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

Note that I encountered a more blocking issue in professional context but it's more difficult to extract a reproduction and the cause is likely similar:
```
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.JDK14LoggerFactory loaded from file:xxx/.m2/repository/org/mock-server/mockserver-junit-jupiter-no-dependencies/5.13.2/mockserver-junit-jupiter-no-dependencies-5.13.2.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.JDK14LoggerFactory
```

**What you are trying to do**
My module instantiate a mock server through the junit 5 extension and is relying on logback for logging.
The specific test falling is not relying on mockserver but starts a simple spring boot application.

**MockServer version**
5.13.2

**To Reproduce**
The binding issue is reproduced with:
- simple project generated from the  [spring initializr with the web dependency](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.6.7&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web)
- with the *mockserver-junit-jupiter-no-dependencies* dependency version 5.13.2

**Idea**
I did not look for the rational behind the *-no-dependencies* artifacts, but the issue comes from the shading jar containing all needed  materials to run mock-server without external dependency.
I'm fine with using the 'standard' dependencies but the documentation indicates the *no-dependency* ones.
The solution may be to simply update the documentation to state the purpose of the different libraries.

I did see the section listing the artifacts (https://mock-server.com/where/maven_central.html) but the choice is not very visible from the main documentation pages.

BTW thanks for your work on this tool.

**Comment by jamesdbloom** [comment]
This is already fixed in this commit: [#2711c33](https://github.com/mock-server/mockserver/commit/2711c33469277fe049d58a8bbaef0b18693e447a)

This is not yet released but will be released in the next few weeks.

**Comment by veysiertekin** [comment]
Hi @jamesdbloom when do you plan a new release. Above fix could be really useful for us.

**Comment by veysiertekin** [comment]
Hi @jamesdbloom , thank you for the fix. when do you plan to make a release? this can be really useful for us.

**Comment by malvarezcastillo** [comment]
Hi @jamesdbloom is there any workaround we can implement until there is a new release? This bug is a blocker for us too.

**Comment by zoltan-toth-mw** [comment]
@jamesdbloom This is still an issue with  `mockserver-junit-jupiter-no-dependencies:5.15.0`, at least with gradle.

`org.mock-server:mockserver-junit-jupiter:5.15.0` works nicely, but the documentation "advertises" the no dependency versions.
```
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.jul.JDK14LoggerFactory loaded from file:/Users/user/.gradle/caches/modules-2/files-2.1/org.mock-server/mockserver-junit-jupiter-no-dependencies/5.15.0/40fd1649b4faff31363e100994bcb0ece8ead3cc/mockserver-junit-jupiter-no-dependencies-5.15.0.jar).
```

**Comment by mgkim-woowahan** [comment]
I have same issue in org.mock-server:mockserver-junit-jupiter-no-dependencies:5.15.0

**Comment by ghost** [comment]
Same with org.mock-server.mockserver-client-java-no-dependencies:5.15.0

**Comment by patrickjamesbarry** [comment]
Since this is still happening in 5.15.0, can this ticket be reopened or do we need to create a new ticket?

**Comment by Mleekko** [comment]
Looks like the "-no-dependencies" artifacts have all the dependencies bundled.
I was able to work around this issue like this:
1. use the version without "-no-dependencies" suffix, exclude `org.slf4j`
```
    testImplementation ('org.mock-server:mockserver-netty:5.15.0') {
        exclude group: 'org.slf4j'
        exclude group: 'junit'
    }
```
2. In the tests, create `MockServerClient` bean.
```
    @Bean
    public MockServerClient mockServerClient() throws IOException {
        return  startClientAndServer(31111);
    }
```
3. Autowire it in the tests
```
    @Autowired
    private MockServerClient mockServerClient;
```
